FORMAT: 1A
HOST: http://localhost:3000

# A Web API Lifecycle

This is our demo API

# API Root [/]

## Retrieve [GET]

+ Response 200 (application/json; charset=utf-8)

        { "data": [ { "id": 1 } ] }
